spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hotel?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123-Patata}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111